[application]

# App (Project) Name
name = "ciggy-buddy"

[web.app]

# HTML title tag content
title = "ciggy-buddy"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "com.ariane"
publisher = "Ariane"
icon = [
    "assets/icons/icon-32x32.png",
    "assets/icons/icon-128x128.png",
    # "assets/icons/icon-128x128@2x.png",
    "assets/icons/icon-256x256.png",
    "assets/icons/icon-512x512.png"
]
resources = ["assets/icons"]